// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx7Yx6hsIhLW9AnAhYR_mAa69VtWAHERM',
    appId: '1:686015607433:web:a80378cef2b42b576fcc58',
    messagingSenderId: '686015607433',
    projectId: 'tiffin-application',
    authDomain: 'tiffin-application.firebaseapp.com',
    storageBucket: 'tiffin-application.appspot.com',
    measurementId: 'G-74ZSKS71JN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq5PZq9O8GgfrrHWWPWhf_2EgcKR0kw1k',
    appId: '1:686015607433:android:dfb86c3b4efde5aa6fcc58',
    messagingSenderId: '686015607433',
    projectId: 'tiffin-application',
    storageBucket: 'tiffin-application.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu9Q_QlC398TickZuZMAbxpzwZc1RMJrE',
    appId: '1:686015607433:ios:4e0e5c1ae977b4c96fcc58',
    messagingSenderId: '686015607433',
    projectId: 'tiffin-application',
    storageBucket: 'tiffin-application.appspot.com',
    androidClientId: '686015607433-nffcvlntivjou8dq9bn41n42h115gnmv.apps.googleusercontent.com',
    iosClientId: '686015607433-d04b721spnd85jamg75un8jnklddj6mc.apps.googleusercontent.com',
    iosBundleId: 'com.example.newTiffinSeller',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu9Q_QlC398TickZuZMAbxpzwZc1RMJrE',
    appId: '1:686015607433:ios:4e0e5c1ae977b4c96fcc58',
    messagingSenderId: '686015607433',
    projectId: 'tiffin-application',
    storageBucket: 'tiffin-application.appspot.com',
    androidClientId: '686015607433-nffcvlntivjou8dq9bn41n42h115gnmv.apps.googleusercontent.com',
    iosClientId: '686015607433-d04b721spnd85jamg75un8jnklddj6mc.apps.googleusercontent.com',
    iosBundleId: 'com.example.newTiffinSeller',
  );
}
